require "http"
require "uri/params"
require "../html"
require "../wording"
require "../http/paths"

module Caramel::I18n
  # The cookie that remembers a browser's chosen locale.
  COOKIE_NAME = "__Host-caramel_locale"
  # An Accept-Language longer than this many bytes is ignored, and only its
  # first 16 ranges are read.
  MAX_ACCEPT_LANGUAGE = 1024
  MAX_RANGES          =   16

  # The locale the current fiber works in: the request's, inside a request.
  # Code generated by `Caramel.locales` defines `Caramel::Locale`.
  def self.locale
    Fiber.current.caramel_locale || ::Caramel::Locale.default
  end

  # Runs the block in *locale*, with *path* as the page a language switcher
  # links from, and restores both afterwards. A `spawn`ed fiber and a Cold
  # Brew job start in the default locale: give a job a `locale` param and
  # wrap its work in
  # `Caramel::I18n.with(Caramel::Locale.parse?(locale) || Caramel::Locale.default) { … }`.
  def self.with(locale, path : String? = Fiber.current.caramel_path, &)
    fiber = Fiber.current
    previous_locale = fiber.caramel_locale
    previous_path = fiber.caramel_path
    fiber.caramel_locale = locale
    fiber.caramel_path = path
    begin
      yield
    ensure
      fiber.caramel_locale = previous_locale
      fiber.caramel_path = previous_path
    end
  end

  # A message from its *parts*: literal text and placeholder values. With a
  # `Caramel::HTML::Safe` value among *args*, the message is safe HTML: the
  # text and every other value are escaped, and safe values are written as
  # they are. Otherwise it is plain text, which a view escapes.
  def self.compose(parts : P, args : A) forall P, A
    {% if A.keys.any? { |key| A[key] <= ::Caramel::HTML::Safe } %}
      html = String.build do |io|
        parts.each do |part|
          io << (part.is_a?(::Caramel::HTML::Safe) ? part.value : ::Caramel::HTML.escape(part))
        end
      end
      ::Caramel::HTML::Safe.new(html)
    {% else %}
      String.build { |io| parts.each { |part| io << part } }
    {% end %}
  end

  # *value* with *locale*'s decimal separator and thousands delimiter.
  def self.number(locale,
                  value : Int::Primitive | Float::Primitive,
                  decimals : Int32? = nil) : String
    value.format(locale.separator, locale.delimiter, decimals)
  end

  # *time*, in its own location, in *pattern* with *locale*'s names.
  # `Caramel.locales` checks that a pattern uses only the directives in
  # `DIRECTIVES`.
  def self.format_time(time : Time, pattern : String, locale) : String
    String.build do |io|
      reader = Char::Reader.new(pattern)
      while reader.has_next?
        char = reader.current_char
        reader.next_char
        next io << char unless char == '%'
        unpadded = reader.current_char == '-'
        reader.next_char if unpadded
        write_directive(io, reader.current_char, time, locale, unpadded)
        reader.next_char
      end
    end
  end

  # The declared locale an Accept-Language *header* prefers: ranges by
  # weight, then by order; an exact tag first, then the first locale in the
  # range's language (`en-GB` finds `en`, `pt` finds `pt-BR`). Nil when no
  # range matches.
  def self.negotiate(header : String)
    return if header.bytesize > MAX_ACCEPT_LANGUAGE
    ranges = header.split(',', MAX_RANGES + 1).first(MAX_RANGES)
    weighted = ranges.map_with_index do |range, index|
      tag, _, parameters = range.partition(';')
      {tag.strip, quality(parameters), index}
    end
    weighted.reject! { |(_, weight, _)| weight.zero? }
    weighted.sort_by! { |(_, weight, index)| {-weight, index} }
    weighted.each do |(tag, _, _)|
      next if tag == "*"
      found = ::Caramel::Locale.parse?(tag) || in_language(tag)
      return found if found
    end
  end

  # The cookie that remembers *locale* for a year.
  def self.cookie(locale) : HTTP::Cookie
    HTTP::Cookie.new(
      COOKIE_NAME,
      locale.code,
      path: "/",
      secure: true,
      http_only: true,
      samesite: HTTP::Cookie::SameSite::Lax,
      max_age: 365.days,
    )
  end

  # *path* under *locale*'s prefix, when the application uses prefixes and
  # *locale* is not the default; otherwise *path*.
  def self.prefixed(locale, path : String) : String
    return path unless PREFIX
    return path if locale.default?
    prefix = "/#{locale.code.downcase}"
    return prefix if path == "/"
    path.starts_with?("/?") ? prefix + path.lchop('/') : prefix + path
  end

  # The current page in *target*: under its prefix, or with `?locale=`.
  def self.switch_path(target) : String
    path = Fiber.current.caramel_path || "/"
    return ::Caramel.tenant_path(prefixed(target, path)) if PREFIX && !target.default?
    separator = path.includes?('?') ? '&' : '?'
    ::Caramel.tenant_path("#{path}#{separator}locale=#{target.code}")
  end

  # With prefixes, the locale a `/CODE` first segment names, which is then
  # removed from *request*'s path. Only a locale's lowercase code is its
  # prefix, and the default locale has none.
  def self.unprefix(request : HTTP::Request)
    return unless PREFIX
    segment, _, rest = request.path.lchop('/').partition('/')
    locale = ::Caramel::Locale.parse?(segment) || return
    return if locale.default? || segment != locale.code.downcase
    request.path = "/" + rest
    locale
  end

  # The answer to a GET or HEAD whose `locale` parameter names a declared
  # locale: remember it and load the same page in it, without the parameter.
  def self.switch(request : HTTP::Request) : Response?
    return unless {"GET", "HEAD"}.includes?(request.method)
    return unless request.query.try(&.includes?("locale"))
    code = request.query_params["locale"]? || return
    locale = ::Caramel::Locale.parse?(code) || return
    query = without_locale(request.query)
    page = query ? "#{request.path}?#{query}" : request.path
    target = ::Caramel.tenant_path(prefixed(locale, page))
    response = begin
      Response.redirect(target, 303)
    rescue ArgumentError
      return
    end
    if request.headers["HX-Request"]? == "true"
      response = Response.new(200, "", HTTP::Headers{"HX-Redirect" => target})
    end
    response.headers["Vary"] = "HX-Request"
    response.headers["Cache-Control"] = "no-store"
    response.headers.add("Set-Cookie", cookie(locale).to_set_cookie_header)
    response
  end

  # The locale the request's cookie remembers, or nil.
  def self.remembered(request : HTTP::Request)
    value = request.cookies[COOKIE_NAME]?.try(&.value) || return
    ::Caramel::Locale.parse?(value)
  end

  # The request's page, for a language switcher: its path and its query
  # without `locale`.
  def self.page(request : HTTP::Request) : String
    query = without_locale(request.query)
    query ? "#{request.path}?#{query}" : request.path
  end

  # *query* without its `locale` parameters; nil when nothing remains.
  private def self.without_locale(query : String?) : String?
    return query.presence unless query && query.includes?("locale")
    params = URI::Params.parse(query)
    params.delete_all("locale")
    params.empty? ? nil : params.to_s
  end

  # The first declared locale in *tag*'s language.
  private def self.in_language(tag : String)
    language = tag.partition('-')[0]
    ::Caramel::Locale.each do |locale|
      own = locale.code.partition('-')[0]
      return locale if own.compare(language, case_insensitive: true) == 0
    end
  end

  # A range's weight: 1 without parameters, else its `q`, from 0 to 1. A
  # malformed or non-finite `q` weighs 0.
  private def self.quality(parameters : String) : Float64
    parameters = parameters.strip
    return 1.0 if parameters.empty?
    name, _, value = parameters.partition('=')
    return 0.0 unless name.strip.compare("q", case_insensitive: true) == 0
    weight = value.strip.to_f? || return 0.0
    weight.finite? ? weight.clamp(0.0, 1.0) : 0.0
  end

  private def self.write_directive(io : IO,
                                   directive : Char,
                                   time : Time,
                                   locale,
                                   unpadded : Bool) : Nil
    case directive
    when '%'                     then io << '%'
    when 'p', 'B', 'b', 'A', 'a' then write_name(io, directive, time, locale)
    else
      value = clock_value(directive, time)
      io << '0' if value < 10 && !unpadded && directive != 'Y'
      io << value
    end
  end

  private def self.write_name(io : IO, directive : Char, time : Time, locale) : Nil
    day = time.day_of_week.value % 7
    case directive
    when 'p' then io << (time.hour < 12 ? locale.am : locale.pm)
    when 'B' then io << locale.months[time.month - 1]
    when 'b' then io << locale.abbr_months[time.month - 1]
    when 'A' then io << locale.days[day]
    else          io << locale.abbr_days[day]
    end
  end

  private def self.clock_value(directive : Char, time : Time) : Int32
    case directive
    when 'Y' then time.year
    when 'm' then time.month
    when 'd' then time.day
    when 'H' then time.hour
    when 'I' then time.hour % 12 == 0 ? 12 : time.hour % 12
    when 'M' then time.minute
    else          time.second
    end
  end
end

module Caramel
  # The request locale's code.
  def self.language : String
    I18n.locale.code
  end

  # *path* under the request locale's prefix, when the application uses
  # prefixes and the locale is not the default.
  def self.localize_path(path : String) : String
    I18n.prefixed(I18n.locale, path)
  end

  module CommandLine
    # Lists the keys each locale takes from the default locale, one
    # `MISSING code key file` line each, and returns 1 while any is missing.
    def self.translations(root : String) : Int32
      missing = I18n::MISSING
      if missing.empty?
        puts "OK #{::Caramel::Locale.values.size} locales, #{I18n::KEYS} keys"
        return 0
      end
      missing.each do |(code, key, file)|
        puts "MISSING #{code} #{key} #{Path[file].relative_to(root)}"
      end
      locales = missing.map(&.[0]).uniq!.size
      puts "#{missing.size} missing in #{locales} locales"
      1
    end
  end
end
